spring:
  application:
    name: cloud-consumer
  zipkin:
    base-url: http://101.133.133.164:9411
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

